version: "3.9"

services:
  web:
    build: .
    image: nuxt-ep-app:latest
    container_name: nuxt-ep-app
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - MONGO_URI=${MONGO_URI}
      - NITRO_HOST=0.0.0.0
      - NITRO_PORT=3000
    expose:
      - "3000"
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: nuxt-ep-nginx
    ports:
      - "8080:8080"
    volumes:
      - ./deploy/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - web
    restart: unless-stopped
